### PR TITLE
many sorting algorithms added in Python language

### PR DESCRIPTION
**Pull request by rudraneel18**
If you like this PR kindly accept it under the hacktoberfest2021, hacktoberfest-accepted tag. Its a pleasure to make this PR for your repo. :)

### CODE REVIEW

**Comment by kothariji** [comment]
Hey @rudraneel18 , First of all thank you so much for creating a PR.

But as you can see, we already have
- Bucket
- Count
- Heap
- Merge
- Radix

So , can you remove those repetitive files from the PR.
Thanks 🙏

**Comment by rudraneel18** [comment]
ya sure...I'll be adding the "PYTHON" before their name right away

**Comment by rudraneel18** [comment]
should I rename the other file names too like putting a JAVA or a CPP in front of their names?

**Comment by kothariji** [comment]
@rudraneel18 no, its fine. For now you can simply do that for python files

**Comment by rudraneel18** [comment]
Done could you please review it once? 
Also a kind request if the tag could be changed to hacktoberfest2021 cause it is not getting updated in my hacktober profile

**Review by kothariji — APPROVED** [review]
Thank you so much for the contributions 🚀

**Comment by kothariji** [comment]
@rudraneel18 I have added a label now, and merged it. Please check if it reflects. If not Please let me know

**Comment by rudraneel18** [comment]
Yes, but will I have to do anything more? Since this is my first time of opensource contribution I m a bit clueless.
Here's a snippet of the hactober fest page
image

**Pull request merged**
