### PR TITLE
(Geeksforgeeks) Palindrome String.cpp

### PR DESCRIPTION
**Pull request by Pradhyuman12**

### CODE REVIEW

**Comment by kothariji** [comment]
Hey @Pradhyuman12 
Thank you so much for the Pull Request
But can you use the proper extension of file...like `.cpp for C++, .py for Python

**Comment by Pradhyuman12** [comment]
Okay I'll do that

**Comment by Pradhyuman12** [comment]
I have changed it, can you pls approve it. 
Thank you so much 💯 👍

**Review by kothariji — APPROVED** [review]
Thanks for the Contributions 🚀

**Pull request merged**
