### PR TITLE
(Two problems and solution of competitive programming)

### PR DESCRIPTION
**Pull request by ShubhangiShrestha**

### CODE REVIEW

**Review by kothariji — COMMENTED** [review]
Please do no make a separate folder for this.

**Comment by ShubhangiShrestha** [comment]
Ok , I will do this in a file

**Comment by ShubhangiShrestha** [comment]
Did that

**Comment by ShubhangiShrestha** [comment]
Ok, I will delete it

**Comment by ShubhangiShrestha** [comment]
Thankyou , for making it hacktoberfest-accepted

**Pull request merged**
